const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.video,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Bgm: 0},
	{Keyboard: 0},
	{CombatBG: 0},
	{HPPlayer: 0},
	{CDUlti: 0},
	{Flash: 0},
	{Knight: 0},
	{Shadow: 0},
	{HP: 0},
	{Enemy: 0},
	{Ulti: 0},
	{Video: 0},
	{Attack: 0},
	{Ultimate: 0},
	{HPEnemy: 0},
	{UIcombat: 0},
	{CombatCommand: 0},
	{SelectLevel: 0},
	{Lv1: 0},
	{MainMenuBG: 0},
	{MainUi: 0},
	{MenuBT: 0},
	{Title: 0},
	{Fade: 0},
	{Ready: 0},
	{Win: 0},
	{Lose: 0},
	{CD: 0},
	{inputsEnabled: 0},
	{UltiCD: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Bgm: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	CombatBG: class extends self.ITiledBackgroundInstance {},
	Knight: class extends self.ISpriteInstance {},
	Shadow: class extends self.ITiledBackgroundInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Ulti: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Attack: class extends self.ISpriteInstance {},
	Ultimate: class extends self.IWorldInstance {},
	HPPlayer: class extends self.ISpriteFontInstance {},
	HPEnemy: class extends self.ISpriteFontInstance {},
	UIcombat: class extends self.ISpriteInstance {},
	CombatCommand: class extends self.ISpriteFontInstance {},
	SelectLevel: class extends self.ISpriteInstance {},
	Lv1: class extends self.ISpriteInstance {},
	MainMenuBG: class extends self.ISpriteInstance {},
	MainUi: class extends self.ISpriteInstance {},
	MenuBT: class extends self.ITextInstance {},
	Title: class extends self.ITextInstance {},
	Ready: class extends self.ITextInstance {},
	Win: class extends self.ITextInstance {},
	Lose: class extends self.ITextInstance {},
	CDUlti: class extends self.ITextInstance {},
	CD: class extends self.ITextInstance {}
}