const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Cnds.OnStep,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.SetTimescale
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Keyboard: 0},
	{state: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{playercollision: 0},
	{Pin: 0},
	{playerAnimation: 0},
	{speed: 0},
	{Ammo: 0},
	{damage: 0},
	{playerGun: 0},
	{Bullet: 0},
	{bullet: 0},
	{Solid: 0},
	{pembatas: 0},
	{Pathfinding: 0},
	{EnemySpawnPoint: 0},
	{Health: 0},
	{State: 0},
	{MoveTo: 0},
	{LineOfSight: 0},
	{EnemyCollision: 0},
	{EnemyUID: 0},
	{Zombie: 0},
	{BGMenu: 0},
	{play: 0},
	{exit: 0},
	{pause: 0},
	{Browser: 0},
	{BGGame: 0},
	{wall: 0},
	{cahaya: 0},
	{BGGame2: 0},
	{Text: 0},
	{Audio: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{TotalSpawned: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	playercollision: class extends self.ISpriteInstance {},
	playerAnimation: class extends self.ISpriteInstance {},
	playerGun: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	pembatas: class extends self.ISpriteInstance {},
	EnemySpawnPoint: class extends self.ISpriteInstance {},
	EnemyCollision: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	BGMenu: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BGGame: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	cahaya: class extends self.ISpriteInstance {},
	BGGame2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}