const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{PinggiranPlay: 0},
	{BuatPlay: 0},
	{Tekan: 0},
	{HP: 0},
	{invincible: 0},
	{zoneID: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Timer: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Player: 0},
	{Keyboard: 0},
	{TPlay: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{BuatATK: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite: 0},
	{Enemy: 0},
	{hitSpawned: 0},
	{ATKEnemy: 0},
	{Spike: 0},
	{Sine: 0},
	{Spike2: 0},
	{MovingBlock: 0},
	{MovingBlock2: 0},
	{Spike3: 0},
	{ATKBuatSpike: 0},
	{Respawn: 0},
	{Ladder: 0},
	{Ladder2: 0},
	{BG1: 0},
	{Nembak: 0},
	{Penembak: 0},
	{Bullet: 0},
	{PlayerPlay: 0},
	{Menu: 0},
	{OnOFAudio: 0},
	{Sprite3: 0},
	{Silang: 0},
	{TombolAudio: 0},
	{Audio: 0},
	{soundOn: 0},
	{OnOff: 0},
	{TombolMenu: 0},
	{Sprite2: 0},
	{Pagar: 0},
	{Hiasan: 0},
	{Hiasan2: 0},
	{Hiasan3: 0},
	{Block: 0},
	{Hiasan4: 0},
	{Hiasan5: 0},
	{Hiasan6: 0},
	{Hiasan7: 0},
	{Hiasan8: 0},
	{Finish: 0},
	{Hiasan9: 0},
	{Hiasan10: 0},
	{Hiasan11: 0},
	{Hiasan12: 0},
	{Player1: 0},
	{Player2: 0},
	{Hiasan13: 0},
	{Hiasan14: 0},
	{Hiasan15: 0},
	{Hiasan16: 0},
	{Hiasan17: 0},
	{Hiasan18: 0},
	{Hiasan19: 0},
	{Hiasan20: 0},
	{Hiasan21: 0},
	{Hiasan22: 0},
	{Hiasan23: 0},
	{Hiasan24: 0},
	{Hiasan25: 0},
	{Hiasan26: 0},
	{Hiasan27: 0},
	{Hiasan28: 0},
	{Hiasan29: 0},
	{Hiasan30: 0}
];

self.InstanceType = {
	PinggiranPlay: class extends self.ISpriteInstance {},
	BuatPlay: class extends self.ISpriteInstance {},
	Tekan: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TPlay: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	BuatATK: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	ATKEnemy: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	Spike2: class extends self.ISpriteInstance {},
	MovingBlock: class extends self.ISpriteInstance {},
	MovingBlock2: class extends self.ISpriteInstance {},
	Spike3: class extends self.ISpriteInstance {},
	ATKBuatSpike: class extends self.ISpriteInstance {},
	Respawn: class extends self.ISpriteInstance {},
	Ladder: class extends self.ISpriteInstance {},
	Ladder2: class extends self.ISpriteInstance {},
	BG1: class extends self.ISpriteInstance {},
	Penembak: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	PlayerPlay: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	OnOFAudio: class extends self.ITilemapInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Silang: class extends self.ISpriteInstance {},
	TombolAudio: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	OnOff: class extends self.ISpriteInstance {},
	TombolMenu: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Pagar: class extends self.ISpriteInstance {},
	Hiasan: class extends self.ISpriteInstance {},
	Hiasan2: class extends self.ISpriteInstance {},
	Hiasan3: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Hiasan4: class extends self.ISpriteInstance {},
	Hiasan5: class extends self.ISpriteInstance {},
	Hiasan6: class extends self.ISpriteInstance {},
	Hiasan7: class extends self.ISpriteInstance {},
	Hiasan8: class extends self.ISpriteInstance {},
	Finish: class extends self.ISpriteInstance {},
	Hiasan9: class extends self.ISpriteInstance {},
	Hiasan10: class extends self.ISpriteInstance {},
	Hiasan11: class extends self.ISpriteInstance {},
	Hiasan12: class extends self.ISpriteInstance {},
	Player1: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Hiasan13: class extends self.ISpriteInstance {},
	Hiasan14: class extends self.ISpriteInstance {},
	Hiasan15: class extends self.ISpriteInstance {},
	Hiasan16: class extends self.ISpriteInstance {},
	Hiasan17: class extends self.ISpriteInstance {},
	Hiasan18: class extends self.ISpriteInstance {},
	Hiasan19: class extends self.ISpriteInstance {},
	Hiasan20: class extends self.ISpriteInstance {},
	Hiasan21: class extends self.ISpriteInstance {},
	Hiasan22: class extends self.ISpriteInstance {},
	Hiasan23: class extends self.ISpriteInstance {},
	Hiasan24: class extends self.ISpriteInstance {},
	Hiasan25: class extends self.ISpriteInstance {},
	Hiasan26: class extends self.ISpriteInstance {},
	Hiasan27: class extends self.ISpriteInstance {},
	Hiasan28: class extends self.ISpriteInstance {},
	Hiasan29: class extends self.ISpriteInstance {},
	Hiasan30: class extends self.ISpriteInstance {}
}