const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{lantai: 0},
	{doubleJump: 0},
	{invul: 0},
	{Platform: 0},
	{Timer: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{player: 0},
	{Keyboard: 0},
	{Tilemap: 0},
	{Sine: 0},
	{movingobject: 0},
	{Sprite: 0},
	{movingobject2: 0},
	{movingobject3: 0},
	{basic_spikes: 0},
	{moving_spike2: 0},
	{basic_spike2: 0},
	{LineOfSight: 0},
	{enemy_ai: 0},
	{respawn_object: 0},
	{uang: 0},
	{HUDLOOK: 0},
	{helt_bar: 0},
	{uangtext: 0},
	{camera: 0},
	{stopwatch: 0},
	{Audio: 0},
	{bgM: 0},
	{Sprite2: 0},
	{namagame: 0},
	{Start: 0},
	{Exit: 0},
	{Touch: 0},
	{Browser: 0},
	{Text: 0},
	{gameSelesai: 0},
	{healt: 0},
	{seconds: 0},
	{minute: 0}
];

self.InstanceType = {
	lantai: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	movingobject: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	movingobject2: class extends self.ISpriteInstance {},
	movingobject3: class extends self.ISpriteInstance {},
	basic_spikes: class extends self.ISpriteInstance {},
	moving_spike2: class extends self.ISpriteInstance {},
	basic_spike2: class extends self.ISpriteInstance {},
	enemy_ai: class extends self.ISpriteInstance {},
	respawn_object: class extends self.ISpriteInstance {},
	uang: class extends self.ISpriteInstance {},
	HUDLOOK: class extends self.ISpriteInstance {},
	helt_bar: class extends self.ISpriteInstance {},
	uangtext: class extends self.ITextInstance {},
	camera: class extends self.ISpriteInstance {},
	stopwatch: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	bgM: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	namagame: class extends self.ITextInstance {},
	Start: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	gameSelesai: class extends self.ITextInstance {}
}