const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{BgGame: 0},
	{objectPertanyaan: 0},
	{urutan: 0},
	{huruf: 0},
	{target: 0},
	{Tween: 0},
	{Sine: 0},
	{key: 0},
	{nyawa: 0},
	{gameOverObj: 0},
	{Fade: 0},
	{Touch: 0},
	{scoreObj: 0},
	{Pin: 0},
	{scoreTxt: 0},
	{ProyekBaru82CE8FE7D: 0},
	{Audio: 0},
	{ProyekBaru935CEA2DF2: 0},
	{ProyekBaru83FC5666F2: 0},
	{ProyekBaru93872BAA: 0},
	{Urutan: 0},
	{TempFrame: 0},
	{TempKey: 0},
	{TotalTarget: 0},
	{Nyawa: 0}
];

self.InstanceType = {
	BgGame: class extends self.ISpriteInstance {},
	objectPertanyaan: class extends self.ISpriteInstance {},
	target: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	nyawa: class extends self.ISpriteInstance {},
	gameOverObj: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	scoreObj: class extends self.ISpriteInstance {},
	scoreTxt: class extends self.ITextInstance {},
	ProyekBaru82CE8FE7D: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	ProyekBaru935CEA2DF2: class extends self.ISpriteInstance {},
	ProyekBaru83FC5666F2: class extends self.ISpriteInstance {},
	ProyekBaru93872BAA: class extends self.ISpriteInstance {}
}