const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{StartBg: 0},
	{posX: 0},
	{posY: 0},
	{panjang: 0},
	{tinggi: 0},
	{Size: 0},
	{Atas: 0},
	{Bawah: 0},
	{Kanan: 0},
	{Kiri: 0},
	{mainMenuTxt: 0},
	{soundBtn: 0},
	{exitBtn: 0},
	{blackTrans: 0},
	{Touch: 0},
	{Browser: 0},
	{MenuLevelGame: 0},
	{Solid: 0},
	{Tilemap: 0},
	{spawnPlayerObj: 0},
	{invul: 0},
	{nomorLevel: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Flash: 0},
	{player: 0},
	{offSideGame: 0},
	{spikes: 0},
	{finishPixel: 0},
	{ParticlesCoins: 0},
	{cek: 0},
	{Sine: 0},
	{enemySkull: 0},
	{Level: 0},
	{nomorFrameMateri: 0},
	{levelSetting: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Tween: 0},
	{coin: 0},
	{hudCoinTimer: 0},
	{NomorLevel: 0},
	{coinTxt: 0},
	{nyawa: 0},
	{mirror: 0},
	{enemyFix: 0},
	{scoreTxt: 0},
	{SoalPilgan: 0},
	{leftBtn: 0},
	{rightBtn: 0},
	{jumpBtn: 0},
	{Pin: 0},
	{siputDetector: 0},
	{mulaiBtn: 0},
	{mainMenuDekor: 0},
	{intro: 0},
	{PetunjukBg: 0},
	{backBtn2: 0},
	{TentangAplikasiBg: 0},
	{nextBtn: 0},
	{platform: 0},
	{homeBtn: 0},
	{gembok: 0},
	{gameOverObj: 0},
	{restartBtn: 0},
	{nextBtnPenjelasan: 0},
	{HasilAkhirBg: 0},
	{Bg: 0},
	{dekorIntro: 0},
	{winGameObj: 0},
	{rightBtn2: 0},
	{Enemy: 0},
	{Btn: 0},
	{Animasi: 0},
	{Music: 0},
	{Level1: 0},
	{Level2: 0},
	{ScoreLevel1: 0},
	{ScoreLevel2: 0},
	{Health: 0},
	{Coins: 0}
];

self.InstanceType = {
	StartBg: class extends self.ISpriteInstance {},
	mainMenuTxt: class extends self.ISpriteInstance {},
	soundBtn: class extends self.ISpriteInstance {},
	exitBtn: class extends self.ISpriteInstance {},
	blackTrans: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MenuLevelGame: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	spawnPlayerObj: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	offSideGame: class extends self.ISpriteInstance {},
	spikes: class extends self.ISpriteInstance {},
	finishPixel: class extends self.ISpriteInstance {},
	ParticlesCoins: class extends self.IParticlesInstance {},
	enemySkull: class extends self.ISpriteInstance {},
	levelSetting: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	coin: class extends self.ISpriteInstance {},
	hudCoinTimer: class extends self.ISpriteInstance {},
	coinTxt: class extends self.ITextInstance {},
	nyawa: class extends self.ISpriteInstance {},
	enemyFix: class extends self.ISpriteInstance {},
	scoreTxt: class extends self.ITextInstance {},
	SoalPilgan: class extends self.ISpriteInstance {},
	leftBtn: class extends self.ISpriteInstance {},
	rightBtn: class extends self.ISpriteInstance {},
	jumpBtn: class extends self.ISpriteInstance {},
	siputDetector: class extends self.ISpriteInstance {},
	mulaiBtn: class extends self.ISpriteInstance {},
	mainMenuDekor: class extends self.ISpriteInstance {},
	intro: class extends self.ISpriteInstance {},
	PetunjukBg: class extends self.ISpriteInstance {},
	backBtn2: class extends self.ISpriteInstance {},
	TentangAplikasiBg: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	gembok: class extends self.ISpriteInstance {},
	gameOverObj: class extends self.ISpriteInstance {},
	restartBtn: class extends self.ISpriteInstance {},
	nextBtnPenjelasan: class extends self.ISpriteInstance {},
	HasilAkhirBg: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	dekorIntro: class extends self.ISpriteInstance {},
	winGameObj: class extends self.ISpriteInstance {},
	rightBtn2: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Btn: class extends self.ISpriteInstance {},
	Animasi: class extends self.ISpriteInstance {}
}