const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{Bg: 0},
	{TileMovement: 0},
	{player: 0},
	{titik: 0},
	{rintangan: 0},
	{Sine: 0},
	{golden_trophy: 0},
	{Solid: 0},
	{pembatas: 0},
	{leftMobileUi: 0},
	{upMobileUi: 0},
	{rightMobileUi: 0},
	{downMobileUi: 0},
	{Touch: 0},
	{papanKayu: 0},
	{Score: 0},
	{Salah: 0},
	{Waktu: 0},
	{rintangan2: 0},
	{Audio: 0},
	{Fade: 0},
	{Bg2: 0},
	{Judul: 0},
	{Level1: 0},
	{Text: 0},
	{PlayTxt: 0},
	{Exit: 0},
	{Level2: 0},
	{homeremovebgpreview: 0},
	{Browser: 0},
	{GameOn: 0}
];

self.InstanceType = {
	Bg: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	titik: class extends self.ISpriteInstance {},
	rintangan: class extends self.ISpriteInstance {},
	golden_trophy: class extends self.ISpriteInstance {},
	pembatas: class extends self.ISpriteInstance {},
	leftMobileUi: class extends self.ISpriteInstance {},
	upMobileUi: class extends self.ISpriteInstance {},
	rightMobileUi: class extends self.ISpriteInstance {},
	downMobileUi: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	papanKayu: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Salah: class extends self.ITextInstance {},
	Waktu: class extends self.ITextInstance {},
	rintangan2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Bg2: class extends self.ISpriteInstance {},
	Judul: class extends self.ITextInstance {},
	Level1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	PlayTxt: class extends self.ITextInstance {},
	Exit: class extends self.ISpriteInstance {},
	Level2: class extends self.ISpriteInstance {},
	homeremovebgpreview: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}