const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{human: 0},
	{Bullet: 0},
	{yCar: 0},
	{spawnerkiri1: 0},
	{rCar: 0},
	{spwnrkanan1: 0},
	{AdvancedRandom: 0},
	{bcar: 0},
	{spwnrkanan2: 0},
	{spwnerkiri2: 0},
	{TiledBackground: 0},
	{UkuranX: 0},
	{UkuranY: 0},
	{Tween: 0},
	{Sprite: 0},
	{Pin: 0},
	{kotak: 0},
	{Touch: 0},
	{Text: 0},
	{ukuranx: 0},
	{ukurany: 0},
	{Sprite2: 0},
	{menu: 0},
	{silang: 0},
	{Text2: 0},
	{ukuranX: 0},
	{ukuranY: 0},
	{Sprite3: 0},
	{Audio: 0},
	{UiWin: 0},
	{Sprite4: 0},
	{star2: 0},
	{star3: 0},
	{restart: 0},
	{back: 0},
	{TiledBackground2: 0},
	{KOTAK: 0},
	{JUMLAH: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	human: class extends self.ISpriteInstance {},
	yCar: class extends self.ISpriteInstance {},
	spawnerkiri1: class extends self.ISpriteInstance {},
	rCar: class extends self.ISpriteInstance {},
	spwnrkanan1: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	bcar: class extends self.ISpriteInstance {},
	spwnrkanan2: class extends self.ISpriteInstance {},
	spwnerkiri2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	kotak: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	silang: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	UiWin: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	star2: class extends self.ISpriteInstance {},
	star3: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {}
}