const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{lantai: 0},
	{Solid: 0},
	{tembok: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{minirobot: 0},
	{Gem: 0},
	{SE: 0},
	{Item: 0},
	{pintu: 0},
	{keluar1: 0},
	{mulai1: 0},
	{Mouse: 0},
	{lantai2: 0},
	{tembok2: 0},
	{GemAsli: 0},
	{kakgem: 0},
	{pintuasli: 0},
	{pintupalsu: 0},
	{keluar2: 0},
	{pintusalah: 0},
	{item2: 0},
	{bgmenu: 0},
	{tombolmulai: 0},
	{Touch: 0},
	{judul: 0},
	{bgmenu1: 0},
	{tombolmenu: 0},
	{cs: 0},
	{GemCount: 0},
	{GemCount2: 0}
];

self.InstanceType = {
	lantai: class extends self.ITilemapInstance {},
	tembok: class extends self.ITilemapInstance {},
	minirobot: class extends self.ISpriteInstance {},
	Gem: class extends self.ISpriteInstance {},
	SE: class extends self.IInstance {},
	Item: class extends self.ITextInstance {},
	pintu: class extends self.ITilemapInstance {},
	keluar1: class extends self.ITextInstance {},
	mulai1: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	lantai2: class extends self.ITilemapInstance {},
	tembok2: class extends self.ITilemapInstance {},
	GemAsli: class extends self.ISpriteInstance {},
	kakgem: class extends self.ISpriteInstance {},
	pintuasli: class extends self.ITilemapInstance {},
	pintupalsu: class extends self.ITilemapInstance {},
	keluar2: class extends self.ITextInstance {},
	pintusalah: class extends self.ITextInstance {},
	item2: class extends self.ITextInstance {},
	bgmenu: class extends self.ISpriteInstance {},
	tombolmulai: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	judul: class extends self.ISpriteInstance {},
	bgmenu1: class extends self.ISpriteInstance {},
	tombolmenu: class extends self.ISpriteInstance {},
	cs: class extends self.ISpriteInstance {}
}