const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.UserMedia,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{bg: 0},
	{Solid: 0},
	{tanah: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Tween: 0},
	{Physics: 0},
	{palyer: 0},
	{touch: 0},
	{object: 0},
	{objek: 0},
	{duri: 0},
	{UserMedia: 0},
	{Finish: 0},
	{ZoomTarget: 0},
	{zoomtriger: 0},
	{Audio: 0},
	{portal1: 0},
	{thitam: 0},
	{Text: 0},
	{angletriger: 0},
	{portal2: 0},
	{player2: 0},
	{AngleTriger2: 0},
	{portal3: 0},
	{jump: 0},
	{down: 0},
	{Tatempt: 0},
	{Keyboard: 0},
	{Tilemap: 0},
	{bg2: 0},
	{menu: 0},
	{TEXT1: 0},
	{txt1: 0},
	{untouch: 0},
	{gui_background: 0},
	{Tfinish: 0},
	{Tattemp: 0},
	{Bquit: 0},
	{TiledBackground: 0},
	{Brestart: 0},
	{Bplay: 0},
	{GoLAyout: 0},
	{Text2: 0},
	{plays: 0},
	{Tquit: 0},
	{Trestart: 0},
	{paradash: 0},
	{Zoom: 0},
	{target: 0},
	{attempt: 0},
	{Touch: 0}
];

self.InstanceType = {
	bg: class extends self.ITiledBackgroundInstance {},
	tanah: class extends self.ITiledBackgroundInstance {},
	palyer: class extends self.ISpriteInstance {},
	touch: class extends self.IInstance {},
	object: class extends self.ITiledBackgroundInstance {},
	objek: class extends self.ISpriteInstance {},
	duri: class extends self.ISpriteInstance {},
	UserMedia: class extends self.IWorldInstance {},
	Finish: class extends self.ISpriteInstance {},
	zoomtriger: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	portal1: class extends self.ISpriteInstance {},
	thitam: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	angletriger: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	AngleTriger2: class extends self.ISpriteInstance {},
	portal3: class extends self.ISpriteInstance {},
	jump: class extends self.ISpriteInstance {},
	down: class extends self.ISpriteInstance {},
	Tatempt: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	bg2: class extends self.ITiledBackgroundInstance {},
	menu: class extends self.ITilemapInstance {},
	TEXT1: class extends self.ITextInstance {},
	txt1: class extends self.ITextInstance {},
	untouch: class extends self.ISpriteInstance {},
	gui_background: class extends self.ITiledBackgroundInstance {},
	Tfinish: class extends self.ITextInstance {},
	Tattemp: class extends self.ITextInstance {},
	Bquit: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Brestart: class extends self.ITiledBackgroundInstance {},
	Bplay: class extends self.ISpriteInstance {},
	GoLAyout: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	plays: class extends self.ITextInstance {},
	Tquit: class extends self.ITextInstance {},
	Trestart: class extends self.ITextInstance {},
	paradash: class extends self.ITextInstance {}
}