const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.UnloadAudio,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap: 0},
	{BG: 0},
	{Sine: 0},
	{Stiker: 0},
	{uiiia: 0},
	{Stiker3: 0},
	{doublejump: 0},
	{invul: 0},
	{Platform: 0},
	{Timer: 0},
	{Flash: 0},
	{char: 0},
	{Stiker2: 0},
	{Miaw: 0},
	{Keyboard: 0},
	{Spike: 0},
	{Move_Spike: 0},
	{Ball: 0},
	{Audio: 0},
	{Spring: 0},
	{LineOfSight: 0},
	{NPC: 0},
	{Spawn_Objek: 0},
	{Cuy: 0},
	{Coin: 0},
	{HUD: 0},
	{HP: 0},
	{Profil: 0},
	{Text2: 0},
	{ScrollTo: 0},
	{Kamera: 0},
	{Wall: 0},
	{Mouse: 0},
	{Mulai: 0},
	{WIN: 0},
	{Booyah: 0},
	{TextInput: 0},
	{Menu: 0},
	{char2: 0},
	{nyawa: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	BG: class extends self.ISpriteInstance {},
	Stiker: class extends self.ISpriteInstance {},
	uiiia: class extends self.ISpriteInstance {},
	Stiker3: class extends self.ISpriteInstance {},
	char: class extends self.ISpriteInstance {},
	Stiker2: class extends self.ISpriteInstance {},
	Miaw: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Spike: class extends self.ISpriteInstance {},
	Move_Spike: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Spring: class extends self.ISpriteInstance {},
	NPC: class extends self.ISpriteInstance {},
	Spawn_Objek: class extends self.ISpriteInstance {},
	Cuy: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	HP: class extends self.ISpriteInstance {},
	Profil: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Kamera: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Mulai: class extends self.ISpriteInstance {},
	WIN: class extends self.ISpriteInstance {},
	Booyah: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Menu: class extends self.ITextInstance {},
	char2: class extends self.ISpriteInstance {}
}